/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary": "var(--color-on-secondary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "outline": "var(--color-outline)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "surface": "var(--color-surface)",
        "secondary": "var(--color-secondary)",
        "on-primary": "var(--color-on-primary)",
        "background": "var(--color-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "on-background": "var(--color-on-background)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-error": "var(--color-on-error)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "error": "var(--color-error)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "error-container": "var(--color-error-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-container": "var(--color-primary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "primary": "var(--color-primary)",
        "primary-fixed": "var(--color-primary-fixed)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin": "32px",
        "unit": "4px",
        "max_width": "1440px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "xl": "48px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "h1": ["Space Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "1.3", "letterSpacing": "0", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
